name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # 3. Instalar Poetry y dependencias
      - name: Install Poetry and dependencies
        working-directory: Backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 4. Crear el archivo .env usando GitHub Secrets y depuraci칩n adicional
      - name: Create .env file from GitHub Secrets
        working-directory: Backend
        run: |
          echo "Creando archivo .env con los secretos"
          echo "openai_api_key=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "model=${{ secrets.MODEL }}" >> .env
          echo "max_tokens=${{ secrets.MAX_TOKENS }}" >> .env
          echo "temperature=${{ secrets.TEMPERATURE }}" >> .env
          echo "number_of_vectorial_results=${{ secrets.NUMBER_OF_VECTORIAL_RESULTS }}" >> .env
          echo "secret_key=${{ secrets.SECRET_KEY }}" >> .env
          echo "algorithm=${{ secrets.ALGORITHM }}" >> .env
          echo "access_token_expire_minutes=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env
          echo "mongodb_uri=${{ secrets.MONGODB_URI }}" >> .env
          echo "mongodb_name=${{ secrets.MONGODB_NAME }}" >> .env
          echo "email_username=${{ secrets.EMAIL_USERNAME }}" >> .env
          echo "email_password=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "email_from=${{ secrets.EMAIL_FROM }}" >> .env
          echo "email_to=${{ secrets.EMAIL_TO }}" >> .env

      # 5. Verificar que los secretos se han cargado correctamente
      - name: Debug Secrets
        run: |
          echo "Verificando secretos..."
          echo "max_tokens: ${{ secrets.MAX_TOKENS }}"
          echo "temperature: ${{ secrets.TEMPERATURE }}"
          echo "number_of_vectorial_results: ${{ secrets.NUMBER_OF_VECTORIAL_RESULTS }}"
          echo "access_token_expire_minutes: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}"

      # 6. Verificar el contenido del archivo .env
      - name: Verify .env file
        working-directory: Backend
        run: cat .env

      # 7. Cargar variables de entorno desde .env
      - name: Load environment variables
        working-directory: Backend
        run: |
          set -a
          source .env
          set +a

      # 8. Ejecutar pre-commit para an치lisis de c칩digo
      - name: Run pre-commit
        working-directory: Backend
        run: poetry run pre-commit run --all-files

      # 9. Ejecutar pruebas con pytest
      - name: Run tests
        working-directory: Backend
        run: |
          export PYTHONPATH=$(pwd)
          poetry run pytest --cov=app --cov-report=xml test/cases_test.py
